server:
  http:
    addr: 0.0.0.0:8008
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9009
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:495495@tcp(localhost:3306)/db_factory?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8