// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.5

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type BlackJackHTTPServer interface {
	EnterRoom(context.Context, *EnterRoomRequest) (*EnterRoomReply, error)
}

func RegisterBlackJackHTTPServer(s *http.Server, srv BlackJackHTTPServer) {
	r := s.Route("/")
	r.POST("/bj21.v1.BlackJack/EnterRoom", _BlackJack_EnterRoom0_HTTP_Handler(srv))
}

func _BlackJack_EnterRoom0_HTTP_Handler(srv BlackJackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnterRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/bj21.v1.BlackJack/EnterRoom")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnterRoom(ctx, req.(*EnterRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnterRoomReply)
		return ctx.Result(200, reply)
	}
}

type BlackJackHTTPClient interface {
	EnterRoom(ctx context.Context, req *EnterRoomRequest, opts ...http.CallOption) (rsp *EnterRoomReply, err error)
}

type BlackJackHTTPClientImpl struct {
	cc *http.Client
}

func NewBlackJackHTTPClient(client *http.Client) BlackJackHTTPClient {
	return &BlackJackHTTPClientImpl{client}
}

func (c *BlackJackHTTPClientImpl) EnterRoom(ctx context.Context, in *EnterRoomRequest, opts ...http.CallOption) (*EnterRoomReply, error) {
	var out EnterRoomReply
	pattern := "/bj21.v1.BlackJack/EnterRoom"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/bj21.v1.BlackJack/EnterRoom"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
