// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/bj21/v1/bj21.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on EnterRoomRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *EnterRoomRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RoomId

	return nil
}

// EnterRoomRequestValidationError is the validation error returned by
// EnterRoomRequest.Validate if the designated constraints aren't met.
type EnterRoomRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnterRoomRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnterRoomRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnterRoomRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnterRoomRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnterRoomRequestValidationError) ErrorName() string { return "EnterRoomRequestValidationError" }

// Error satisfies the builtin error interface
func (e EnterRoomRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnterRoomRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnterRoomRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnterRoomRequestValidationError{}

// Validate checks the field values on EnterRoomReply with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *EnterRoomReply) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RoomToken

	return nil
}

// EnterRoomReplyValidationError is the validation error returned by
// EnterRoomReply.Validate if the designated constraints aren't met.
type EnterRoomReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnterRoomReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnterRoomReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnterRoomReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnterRoomReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnterRoomReplyValidationError) ErrorName() string { return "EnterRoomReplyValidationError" }

// Error satisfies the builtin error interface
func (e EnterRoomReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnterRoomReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnterRoomReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnterRoomReplyValidationError{}

// Validate checks the field values on ChatContent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ChatContent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Message

	return nil
}

// ChatContentValidationError is the validation error returned by
// ChatContent.Validate if the designated constraints aren't met.
type ChatContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatContentValidationError) ErrorName() string { return "ChatContentValidationError" }

// Error satisfies the builtin error interface
func (e ChatContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatContentValidationError{}
