// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: api/bj21/v1/bj21.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EnterRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *EnterRoomRequest) Reset() {
	*x = EnterRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bj21_v1_bj21_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomRequest) ProtoMessage() {}

func (x *EnterRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bj21_v1_bj21_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomRequest.ProtoReflect.Descriptor instead.
func (*EnterRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_bj21_v1_bj21_proto_rawDescGZIP(), []int{0}
}

func (x *EnterRoomRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type EnterRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomToken string `protobuf:"bytes,1,opt,name=room_token,json=roomToken,proto3" json:"room_token,omitempty"`
}

func (x *EnterRoomReply) Reset() {
	*x = EnterRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bj21_v1_bj21_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomReply) ProtoMessage() {}

func (x *EnterRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bj21_v1_bj21_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomReply.ProtoReflect.Descriptor instead.
func (*EnterRoomReply) Descriptor() ([]byte, []int) {
	return file_api_bj21_v1_bj21_proto_rawDescGZIP(), []int{1}
}

func (x *EnterRoomReply) GetRoomToken() string {
	if x != nil {
		return x.RoomToken
	}
	return ""
}

var File_api_bj21_v1_bj21_proto protoreflect.FileDescriptor

var file_api_bj21_v1_bj21_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x6a, 0x32, 0x31, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6a,
	0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6a, 0x32, 0x31, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2b, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x75, 0x0a,
	0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4a, 0x61, 0x63, 0x6b, 0x12, 0x68, 0x0a, 0x09, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x2e, 0x62, 0x6a, 0x32, 0x31, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x6a, 0x32, 0x31, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x21, 0x22, 0x1c, 0x2f, 0x62, 0x6a, 0x32, 0x31, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x4a, 0x61, 0x63, 0x6b, 0x2f, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f,
	0x6d, 0x3a, 0x01, 0x2a, 0x42, 0x1f, 0x5a, 0x1d, 0x66, 0x78, 0x6b, 0x74, 0x2e, 0x74, 0x65, 0x63,
	0x68, 0x2f, 0x62, 0x6a, 0x32, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x6a, 0x32, 0x31, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_bj21_v1_bj21_proto_rawDescOnce sync.Once
	file_api_bj21_v1_bj21_proto_rawDescData = file_api_bj21_v1_bj21_proto_rawDesc
)

func file_api_bj21_v1_bj21_proto_rawDescGZIP() []byte {
	file_api_bj21_v1_bj21_proto_rawDescOnce.Do(func() {
		file_api_bj21_v1_bj21_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_bj21_v1_bj21_proto_rawDescData)
	})
	return file_api_bj21_v1_bj21_proto_rawDescData
}

var file_api_bj21_v1_bj21_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_bj21_v1_bj21_proto_goTypes = []interface{}{
	(*EnterRoomRequest)(nil), // 0: bj21.v1.EnterRoomRequest
	(*EnterRoomReply)(nil),   // 1: bj21.v1.EnterRoomReply
}
var file_api_bj21_v1_bj21_proto_depIdxs = []int32{
	0, // 0: bj21.v1.BlackJack.EnterRoom:input_type -> bj21.v1.EnterRoomRequest
	1, // 1: bj21.v1.BlackJack.EnterRoom:output_type -> bj21.v1.EnterRoomReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bj21_v1_bj21_proto_init() }
func file_api_bj21_v1_bj21_proto_init() {
	if File_api_bj21_v1_bj21_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_bj21_v1_bj21_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bj21_v1_bj21_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_bj21_v1_bj21_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bj21_v1_bj21_proto_goTypes,
		DependencyIndexes: file_api_bj21_v1_bj21_proto_depIdxs,
		MessageInfos:      file_api_bj21_v1_bj21_proto_msgTypes,
	}.Build()
	File_api_bj21_v1_bj21_proto = out.File
	file_api_bj21_v1_bj21_proto_rawDesc = nil
	file_api_bj21_v1_bj21_proto_goTypes = nil
	file_api_bj21_v1_bj21_proto_depIdxs = nil
}
