// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bj21.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTableReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableReq) Reset()         { *m = CreateTableReq{} }
func (m *CreateTableReq) String() string { return proto.CompactTextString(m) }
func (*CreateTableReq) ProtoMessage()    {}
func (*CreateTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{0}
}

func (m *CreateTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableReq.Unmarshal(m, b)
}
func (m *CreateTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableReq.Marshal(b, m, deterministic)
}
func (m *CreateTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableReq.Merge(m, src)
}
func (m *CreateTableReq) XXX_Size() int {
	return xxx_messageInfo_CreateTableReq.Size(m)
}
func (m *CreateTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableReq proto.InternalMessageInfo

func (m *CreateTableReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateTableRes struct {
	Code                 int32                `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 *CreateTableRes_Data `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTableRes) Reset()         { *m = CreateTableRes{} }
func (m *CreateTableRes) String() string { return proto.CompactTextString(m) }
func (*CreateTableRes) ProtoMessage()    {}
func (*CreateTableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{1}
}

func (m *CreateTableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableRes.Unmarshal(m, b)
}
func (m *CreateTableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableRes.Marshal(b, m, deterministic)
}
func (m *CreateTableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableRes.Merge(m, src)
}
func (m *CreateTableRes) XXX_Size() int {
	return xxx_messageInfo_CreateTableRes.Size(m)
}
func (m *CreateTableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableRes proto.InternalMessageInfo

func (m *CreateTableRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateTableRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateTableRes) GetData() *CreateTableRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateTableRes_Data struct {
	TableIdx             int32    `protobuf:"varint,1,opt,name=TableIdx,proto3" json:"TableIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableRes_Data) Reset()         { *m = CreateTableRes_Data{} }
func (m *CreateTableRes_Data) String() string { return proto.CompactTextString(m) }
func (*CreateTableRes_Data) ProtoMessage()    {}
func (*CreateTableRes_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{2}
}

func (m *CreateTableRes_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableRes_Data.Unmarshal(m, b)
}
func (m *CreateTableRes_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableRes_Data.Marshal(b, m, deterministic)
}
func (m *CreateTableRes_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableRes_Data.Merge(m, src)
}
func (m *CreateTableRes_Data) XXX_Size() int {
	return xxx_messageInfo_CreateTableRes_Data.Size(m)
}
func (m *CreateTableRes_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableRes_Data.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableRes_Data proto.InternalMessageInfo

func (m *CreateTableRes_Data) GetTableIdx() int32 {
	if m != nil {
		return m.TableIdx
	}
	return 0
}

type JoinTableReq struct {
	TableIdx             int32    `protobuf:"varint,1,opt,name=TableIdx,proto3" json:"TableIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTableReq) Reset()         { *m = JoinTableReq{} }
func (m *JoinTableReq) String() string { return proto.CompactTextString(m) }
func (*JoinTableReq) ProtoMessage()    {}
func (*JoinTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{3}
}

func (m *JoinTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTableReq.Unmarshal(m, b)
}
func (m *JoinTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTableReq.Marshal(b, m, deterministic)
}
func (m *JoinTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTableReq.Merge(m, src)
}
func (m *JoinTableReq) XXX_Size() int {
	return xxx_messageInfo_JoinTableReq.Size(m)
}
func (m *JoinTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTableReq proto.InternalMessageInfo

func (m *JoinTableReq) GetTableIdx() int32 {
	if m != nil {
		return m.TableIdx
	}
	return 0
}

type JoinTableRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTableRes) Reset()         { *m = JoinTableRes{} }
func (m *JoinTableRes) String() string { return proto.CompactTextString(m) }
func (*JoinTableRes) ProtoMessage()    {}
func (*JoinTableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{4}
}

func (m *JoinTableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTableRes.Unmarshal(m, b)
}
func (m *JoinTableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTableRes.Marshal(b, m, deterministic)
}
func (m *JoinTableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTableRes.Merge(m, src)
}
func (m *JoinTableRes) XXX_Size() int {
	return xxx_messageInfo_JoinTableRes.Size(m)
}
func (m *JoinTableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTableRes.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTableRes proto.InternalMessageInfo

func (m *JoinTableRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JoinTableRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StartStageReq struct {
	TableIdx             int32    `protobuf:"varint,1,opt,name=TableIdx,proto3" json:"TableIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStageReq) Reset()         { *m = StartStageReq{} }
func (m *StartStageReq) String() string { return proto.CompactTextString(m) }
func (*StartStageReq) ProtoMessage()    {}
func (*StartStageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{5}
}

func (m *StartStageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStageReq.Unmarshal(m, b)
}
func (m *StartStageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStageReq.Marshal(b, m, deterministic)
}
func (m *StartStageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStageReq.Merge(m, src)
}
func (m *StartStageReq) XXX_Size() int {
	return xxx_messageInfo_StartStageReq.Size(m)
}
func (m *StartStageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStageReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartStageReq proto.InternalMessageInfo

func (m *StartStageReq) GetTableIdx() int32 {
	if m != nil {
		return m.TableIdx
	}
	return 0
}

type StartStageRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStageRes) Reset()         { *m = StartStageRes{} }
func (m *StartStageRes) String() string { return proto.CompactTextString(m) }
func (*StartStageRes) ProtoMessage()    {}
func (*StartStageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{6}
}

func (m *StartStageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStageRes.Unmarshal(m, b)
}
func (m *StartStageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStageRes.Marshal(b, m, deterministic)
}
func (m *StartStageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStageRes.Merge(m, src)
}
func (m *StartStageRes) XXX_Size() int {
	return xxx_messageInfo_StartStageRes.Size(m)
}
func (m *StartStageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStageRes.DiscardUnknown(m)
}

var xxx_messageInfo_StartStageRes proto.InternalMessageInfo

func (m *StartStageRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StartStageRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type HITReq struct {
	TableIdx             int32    `protobuf:"varint,1,opt,name=TableIdx,proto3" json:"TableIdx,omitempty"`
	PNumber              int32    `protobuf:"varint,2,opt,name=PNumber,proto3" json:"PNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HITReq) Reset()         { *m = HITReq{} }
func (m *HITReq) String() string { return proto.CompactTextString(m) }
func (*HITReq) ProtoMessage()    {}
func (*HITReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{7}
}

func (m *HITReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HITReq.Unmarshal(m, b)
}
func (m *HITReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HITReq.Marshal(b, m, deterministic)
}
func (m *HITReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HITReq.Merge(m, src)
}
func (m *HITReq) XXX_Size() int {
	return xxx_messageInfo_HITReq.Size(m)
}
func (m *HITReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HITReq.DiscardUnknown(m)
}

var xxx_messageInfo_HITReq proto.InternalMessageInfo

func (m *HITReq) GetTableIdx() int32 {
	if m != nil {
		return m.TableIdx
	}
	return 0
}

func (m *HITReq) GetPNumber() int32 {
	if m != nil {
		return m.PNumber
	}
	return 0
}

type HITRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HITRes) Reset()         { *m = HITRes{} }
func (m *HITRes) String() string { return proto.CompactTextString(m) }
func (*HITRes) ProtoMessage()    {}
func (*HITRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{8}
}

func (m *HITRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HITRes.Unmarshal(m, b)
}
func (m *HITRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HITRes.Marshal(b, m, deterministic)
}
func (m *HITRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HITRes.Merge(m, src)
}
func (m *HITRes) XXX_Size() int {
	return xxx_messageInfo_HITRes.Size(m)
}
func (m *HITRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HITRes.DiscardUnknown(m)
}

var xxx_messageInfo_HITRes proto.InternalMessageInfo

func (m *HITRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HITRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CalcResultReq struct {
	TableIdx             int32    `protobuf:"varint,1,opt,name=TableIdx,proto3" json:"TableIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcResultReq) Reset()         { *m = CalcResultReq{} }
func (m *CalcResultReq) String() string { return proto.CompactTextString(m) }
func (*CalcResultReq) ProtoMessage()    {}
func (*CalcResultReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{9}
}

func (m *CalcResultReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcResultReq.Unmarshal(m, b)
}
func (m *CalcResultReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcResultReq.Marshal(b, m, deterministic)
}
func (m *CalcResultReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcResultReq.Merge(m, src)
}
func (m *CalcResultReq) XXX_Size() int {
	return xxx_messageInfo_CalcResultReq.Size(m)
}
func (m *CalcResultReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcResultReq.DiscardUnknown(m)
}

var xxx_messageInfo_CalcResultReq proto.InternalMessageInfo

func (m *CalcResultReq) GetTableIdx() int32 {
	if m != nil {
		return m.TableIdx
	}
	return 0
}

type CalcResultRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcResultRes) Reset()         { *m = CalcResultRes{} }
func (m *CalcResultRes) String() string { return proto.CompactTextString(m) }
func (*CalcResultRes) ProtoMessage()    {}
func (*CalcResultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb95ea54e30d1810, []int{10}
}

func (m *CalcResultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcResultRes.Unmarshal(m, b)
}
func (m *CalcResultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcResultRes.Marshal(b, m, deterministic)
}
func (m *CalcResultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcResultRes.Merge(m, src)
}
func (m *CalcResultRes) XXX_Size() int {
	return xxx_messageInfo_CalcResultRes.Size(m)
}
func (m *CalcResultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcResultRes.DiscardUnknown(m)
}

var xxx_messageInfo_CalcResultRes proto.InternalMessageInfo

func (m *CalcResultRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CalcResultRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTableReq)(nil), "pb.CreateTableReq")
	proto.RegisterType((*CreateTableRes)(nil), "pb.CreateTableRes")
	proto.RegisterType((*CreateTableRes_Data)(nil), "pb.CreateTableRes_Data")
	proto.RegisterType((*JoinTableReq)(nil), "pb.JoinTableReq")
	proto.RegisterType((*JoinTableRes)(nil), "pb.JoinTableRes")
	proto.RegisterType((*StartStageReq)(nil), "pb.StartStageReq")
	proto.RegisterType((*StartStageRes)(nil), "pb.StartStageRes")
	proto.RegisterType((*HITReq)(nil), "pb.HITReq")
	proto.RegisterType((*HITRes)(nil), "pb.HITRes")
	proto.RegisterType((*CalcResultReq)(nil), "pb.CalcResultReq")
	proto.RegisterType((*CalcResultRes)(nil), "pb.CalcResultRes")
}

func init() { proto.RegisterFile("bj21.proto", fileDescriptor_eb95ea54e30d1810) }

var fileDescriptor_eb95ea54e30d1810 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0x29, 0x2f, 0x65, 0x50, 0x83, 0xe3, 0xc1, 0x66, 0x2f, 0x92, 0x8d, 0x07, 0x22, 0x49,
	0x93, 0x56, 0x8c, 0x37, 0x0f, 0xe2, 0x01, 0x48, 0x24, 0x66, 0xe1, 0x6e, 0x76, 0x61, 0x43, 0x34,
	0x60, 0xa1, 0x5d, 0x12, 0xff, 0x7b, 0xcd, 0x2e, 0xb5, 0x0f, 0x6a, 0xa4, 0xde, 0x66, 0x67, 0x7e,
	0xdf, 0x0c, 0x33, 0x1f, 0x05, 0x10, 0xef, 0x9e, 0xeb, 0xac, 0x03, 0x5f, 0xf9, 0x58, 0x5e, 0x0b,
	0x7a, 0x0d, 0x67, 0xfd, 0x40, 0x72, 0x25, 0xa7, 0x5c, 0x2c, 0x25, 0x93, 0x1b, 0x44, 0xa8, 0x8e,
	0xf9, 0x4a, 0xda, 0x56, 0xdb, 0xea, 0x34, 0x98, 0x89, 0xe9, 0x6c, 0x8f, 0x0a, 0x35, 0xd5, 0xf7,
	0xe7, 0x3b, 0xaa, 0xc6, 0x4c, 0x8c, 0x2d, 0xa8, 0x3c, 0x87, 0x0b, 0xbb, 0x6c, 0x84, 0x3a, 0xc4,
	0x2e, 0x54, 0x9f, 0xb8, 0xe2, 0x76, 0xa5, 0x6d, 0x75, 0x9a, 0xde, 0xa5, 0xb3, 0x16, 0x4e, 0xb6,
	0xcf, 0xab, 0x2e, 0x33, 0x03, 0x51, 0x17, 0x2e, 0x7e, 0x29, 0x22, 0x81, 0x63, 0x93, 0x18, 0xce,
	0x3f, 0xa3, 0x69, 0xf1, 0x9b, 0xde, 0xc0, 0xc9, 0xc8, 0x7f, 0xfb, 0x88, 0x7f, 0xfb, 0x5f, 0x6c,
	0x2f, 0xc3, 0x16, 0xdc, 0x80, 0x76, 0xe1, 0x74, 0xa2, 0x78, 0xa0, 0x26, 0x8a, 0x2f, 0x0e, 0x8e,
	0xb8, 0xcb, 0xc2, 0x45, 0x67, 0x3c, 0x40, 0x7d, 0x30, 0x9c, 0x1e, 0x68, 0x8e, 0x36, 0x1c, 0xbd,
	0x8c, 0xb7, 0x2b, 0x21, 0x03, 0xa3, 0xad, 0xb1, 0x9f, 0x27, 0x75, 0x22, 0xfd, 0x3f, 0x76, 0xea,
	0xf3, 0xe5, 0x8c, 0xc9, 0x70, 0xbb, 0x54, 0x05, 0x76, 0x4a, 0xc3, 0x05, 0x67, 0x78, 0x5f, 0x16,
	0x54, 0x1f, 0x47, 0x9e, 0x8b, 0xf7, 0xd0, 0x4c, 0xb9, 0x8a, 0x98, 0xfb, 0x0f, 0x6c, 0x48, 0x3e,
	0x17, 0xd2, 0x12, 0xba, 0xd0, 0x88, 0xfd, 0xc2, 0x96, 0x46, 0xd2, 0x56, 0x93, 0xfd, 0x8c, 0x96,
	0xf4, 0x00, 0x92, 0xfb, 0xe3, 0xb9, 0x26, 0x32, 0xe6, 0x91, 0x5c, 0x4a, 0xab, 0xae, 0xa0, 0x32,
	0x18, 0x4e, 0x11, 0x74, 0x6d, 0xe7, 0x03, 0x49, 0xe2, 0xa8, 0x6d, 0x72, 0x82, 0x5d, 0xdb, 0xcc,
	0xfd, 0x48, 0x2e, 0x15, 0xd2, 0x92, 0xa8, 0x9b, 0x8f, 0xec, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xe6, 0x76, 0xae, 0xbb, 0x72, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BJ21Client is the client API for BJ21 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BJ21Client interface {
	CreateTable(ctx context.Context, in *CreateTableReq, opts ...grpc.CallOption) (*CreateTableRes, error)
	JoinTable(ctx context.Context, in *JoinTableReq, opts ...grpc.CallOption) (*JoinTableRes, error)
	StartStage(ctx context.Context, in *StartStageReq, opts ...grpc.CallOption) (*StartStageRes, error)
	HIT(ctx context.Context, in *HITReq, opts ...grpc.CallOption) (*HITRes, error)
	CalcResult(ctx context.Context, in *CalcResultReq, opts ...grpc.CallOption) (*CalcResultRes, error)
}

type bJ21Client struct {
	cc *grpc.ClientConn
}

func NewBJ21Client(cc *grpc.ClientConn) BJ21Client {
	return &bJ21Client{cc}
}

func (c *bJ21Client) CreateTable(ctx context.Context, in *CreateTableReq, opts ...grpc.CallOption) (*CreateTableRes, error) {
	out := new(CreateTableRes)
	err := c.cc.Invoke(ctx, "/pb.BJ21/CreateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bJ21Client) JoinTable(ctx context.Context, in *JoinTableReq, opts ...grpc.CallOption) (*JoinTableRes, error) {
	out := new(JoinTableRes)
	err := c.cc.Invoke(ctx, "/pb.BJ21/JoinTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bJ21Client) StartStage(ctx context.Context, in *StartStageReq, opts ...grpc.CallOption) (*StartStageRes, error) {
	out := new(StartStageRes)
	err := c.cc.Invoke(ctx, "/pb.BJ21/StartStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bJ21Client) HIT(ctx context.Context, in *HITReq, opts ...grpc.CallOption) (*HITRes, error) {
	out := new(HITRes)
	err := c.cc.Invoke(ctx, "/pb.BJ21/HIT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bJ21Client) CalcResult(ctx context.Context, in *CalcResultReq, opts ...grpc.CallOption) (*CalcResultRes, error) {
	out := new(CalcResultRes)
	err := c.cc.Invoke(ctx, "/pb.BJ21/CalcResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BJ21Server is the server API for BJ21 service.
type BJ21Server interface {
	CreateTable(context.Context, *CreateTableReq) (*CreateTableRes, error)
	JoinTable(context.Context, *JoinTableReq) (*JoinTableRes, error)
	StartStage(context.Context, *StartStageReq) (*StartStageRes, error)
	HIT(context.Context, *HITReq) (*HITRes, error)
	CalcResult(context.Context, *CalcResultReq) (*CalcResultRes, error)
}

// UnimplementedBJ21Server can be embedded to have forward compatible implementations.
type UnimplementedBJ21Server struct {
}

func (*UnimplementedBJ21Server) CreateTable(ctx context.Context, req *CreateTableReq) (*CreateTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (*UnimplementedBJ21Server) JoinTable(ctx context.Context, req *JoinTableReq) (*JoinTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinTable not implemented")
}
func (*UnimplementedBJ21Server) StartStage(ctx context.Context, req *StartStageReq) (*StartStageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStage not implemented")
}
func (*UnimplementedBJ21Server) HIT(ctx context.Context, req *HITReq) (*HITRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HIT not implemented")
}
func (*UnimplementedBJ21Server) CalcResult(ctx context.Context, req *CalcResultReq) (*CalcResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcResult not implemented")
}

func RegisterBJ21Server(s *grpc.Server, srv BJ21Server) {
	s.RegisterService(&_BJ21_serviceDesc, srv)
}

func _BJ21_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BJ21Server).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BJ21/CreateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BJ21Server).CreateTable(ctx, req.(*CreateTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BJ21_JoinTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BJ21Server).JoinTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BJ21/JoinTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BJ21Server).JoinTable(ctx, req.(*JoinTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BJ21_StartStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BJ21Server).StartStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BJ21/StartStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BJ21Server).StartStage(ctx, req.(*StartStageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BJ21_HIT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HITReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BJ21Server).HIT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BJ21/HIT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BJ21Server).HIT(ctx, req.(*HITReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BJ21_CalcResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BJ21Server).CalcResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BJ21/CalcResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BJ21Server).CalcResult(ctx, req.(*CalcResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BJ21_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BJ21",
	HandlerType: (*BJ21Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _BJ21_CreateTable_Handler,
		},
		{
			MethodName: "JoinTable",
			Handler:    _BJ21_JoinTable_Handler,
		},
		{
			MethodName: "StartStage",
			Handler:    _BJ21_StartStage_Handler,
		},
		{
			MethodName: "HIT",
			Handler:    _BJ21_HIT_Handler,
		},
		{
			MethodName: "CalcResult",
			Handler:    _BJ21_CalcResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bj21.proto",
}
